### ISSUE TITLE
Apakah APInya support untuk menampilkan akurasi ?

### ISSUE THREAD

**Issue by alif25r** [yusufsyaifudin/indonesia-ner#1]
Dear Yusuf,

Apakah dalam API ini bisa menampilkan akurasi dari algoritma tersebut tidak ya ? Jika iya bagaimana ya ??

Terima kasih.

**Comment by yusufsyaifudin** [comment]
@alif25r apa yang dimaksud itu mengetes akurasi, presisi dan recall terhadap model yang telah dibuat dengan data set sendiri? jika iya bisa pakai kelas `TestNerModel` [http://yusufsyaifudin.github.io/indonesia-ner/doc/api/index.html?yusufs/nlp/nerid/TestNerModel.html](http://yusufsyaifudin.github.io/indonesia-ner/doc/api/index.html?yusufs/nlp/nerid/TestNerModel.html)

```
TestNerModel testModel = new TestNerModel();
TestNerModel nertest = testModel.doTest(File testData, NERModel nermodel);
```

kodenya bisa dilihat [di sini ](https://github.com/yusufsyaifudin/indonesia-ner/blob/master/src/main/java/yusufs/nlp/nerid/TestNerModel.java)

atau jika menggunakan model yang sudah ada (menggunakan data set saya) bisa dilihat kode pengetesannya di sini [IndonesiaNERTest.java](https://github.com/yusufsyaifudin/indonesia-ner/blob/master/src/test/java/nerid/IndonesiaNERTest.java) dengan hasil sebagai berikut:

```
{
  "dataCounter": {
    "OTHER": 9526,
    "LOCATION": 213,
    "ORGANIZATION": 323,
    "PERSON": 679,
    "QUANTITY": 39,
    "TIME": 287
  },
  "total": 11067,
  "correct": 1277,
  "missing": 264,
  "wrong": 853,
  "truePositive": 1277,
  "trueNegative": 8673,
  "falsePositive": 853,
  "falseNegative": 264,
  "accuracy": 0.8990693051414114,
  "recall": 0.8286826735885788,
  "precision": 0.5995305164319249,
  "totalKalimat": 512
}
```

**Comment by alif25r** [comment]
iya maksud saya mengetes akurasi, presisi dan recall dan menampilkan hasilnya.
udah saya lakukan tapi kenapa ya ada nilai yang null pada variabel recall ?

tapi sebelumnya saya ingin menanyakan apakah text atau value untuk data train dan test itu sama (sama-sama mendefinisikan NE pada textnya) atau berbeda ?

contoh sama : 
```
data train dan data test menggunakan teks ini (yang ada tag NE nya) : 

<PERSON>Doni</PERSON> berangkat ke <LOCATION>sekolah</LOCATION> dengan tergesa-gesa. 
<PERSON>Dia</PERSON> terlambat bangun. <PERSON>Dia</PERSON> mengerjakan tugas sampai 
larut <TIME>malam</TIME>. <PERSON>Doni</PERSON> bangun <TIME>kesiangan</TIME> karena 
terlalu lelah. <PERSON>Ia</PERSON> jadi terburu-buru karena bangun <TIME>kesiangan</TIME>. 
Sampai di <LOCATION>sekolah</LOCATION>, <PERSON>ia</PERSON> sudah terlambat. 
<PERSON>Ia</PERSON> cepat-cepat menuju <LOCATION>kelas</LOCATION>. Sudah terlambat, 
prakaryanya pun tertinggal. <PERSON>Doni</PERSON> langsung lemas. Prakarya itu 
<PERSON>dia</PERSON> buat hingga larut <TIME>malam</TIME>.
```

contoh beda : 
```
data train :
<PERSON>Doni</PERSON> berangkat ke <LOCATION>sekolah</LOCATION> dengan tergesa-gesa. 
<PERSON>Dia</PERSON> terlambat bangun. <PERSON>Dia</PERSON> mengerjakan tugas sampai 
larut <TIME>malam</TIME>. <PERSON>Doni</PERSON> bangun <TIME>kesiangan</TIME> karena 
terlalu lelah. <PERSON>Ia</PERSON> jadi terburu-buru karena bangun <TIME>kesiangan</TIME>. 
Sampai di <LOCATION>sekolah</LOCATION>, <PERSON>ia</PERSON> sudah terlambat. 
<PERSON>Ia</PERSON> cepat-cepat menuju <LOCATION>kelas</LOCATION>. Sudah terlambat, 
prakaryanya pun tertinggal. <PERSON>Doni</PERSON> langsung lemas. Prakarya itu 
<PERSON>dia</PERSON> buat hingga larut <TIME>malam</TIME>. 

data test : 
Doni berangkat ke sekolah dengan tergesa-gesa. Dia terlambat bangun. Dia mengerjakan tugas sampai 
larut malam. Doni bangun kesiangan karena terlalu lelah. Ia jadi terburu-buru karena bangun kesiangan. 
Sampai di sekolah, ia sudah terlambat. Ia cepat-cepat menuju kelas. Sudah terlambat, prakaryanya pun 
tertinggal. Doni langsung lemas. Prakarya itu dia buat hingga larut malam.
```

untuk saat ini saya menggunakan data train dan test yang berbeda dan hasil yang saya dapatkan :
```
Total Entitas : 64 // total
Tebakan Benar : 0 // correct
Tebakan Gagal : 0 // missing
Tebakan Salah : 61 // wrong
Entitas NE dideteksi NE : 0 // truePositive
Bukan OTHER dideteksi OTHER : 3 // trueNegative
Entitas OTHER dideteksi NE : 61 // falsePositive
Entitas NE dideteksi OTHER : 0 // falseNegative
Akurasi : 4,69% // accuracy
Recall : NaN // recall
Presisi : 0.0 // precision
Total Kalimat : 1 // totalKalimat
```

kode yang dijalankan untuk test  : 
```
// lokasi model buatan saya
File modelFile = new File("./src/main/resources/model/myModel.json");
TestNerModel testModel = new TestNerModel();
testModel.doTest(filePath, model.loadModel(modelFile));
```

Tapi jika saya menggunakan data train dan test yang ada tag NEnya semua value tidak ada yang null.



--- mohon maaf jika bahasa saya sulit dimengerti :(

**Comment by yusufsyaifudin** [comment]
> iya maksud saya mengetes akurasi, presisi dan recall dan menampilkan hasilnya.
udah saya lakukan tapi kenapa ya ada nilai yang null pada variabel recall ?

Ini karena `recall = TP / (TP + FN )` lihat [kode di sini](https://github.com/yusufsyaifudin/indonesia-ner/blob/master/src/main/java/yusufs/nlp/nerid/TestNerModel.java#L61) sedangkan,
TP = 0 dan FN = 0 sehingga 0/0 = NaN (alias **Not a Number**, bukan **null**) 


> tapi sebelumnya saya ingin menanyakan apakah text atau value untuk data train dan test itu sama (sama-sama mendefinisikan NE pada textnya) atau berbeda ?

Baik data train ataupun data test harus merupakan text yang memiliki tag NE, sehingga contoh yang pertama merupakan contoh data yang benar



> untuk saat ini saya menggunakan data train dan test yang berbeda dan hasil yang saya dapatkan :
...

Tampaknya ini karena memang data tesnya tidak memiliki NE, dapat dilihat dari Entitas NE dideteksi NE (truePositive) berjumlah nol. Meski kadang hal ini juga dapat terjadi jika data train terlampau kecil. 

> Tapi jika saya menggunakan data train dan test yang ada tag NEnya semua value tidak ada yang null.

Memang seharusnya begitu, data train dan data test harus memiliki tag NE. Kenapa? Karena tag NE pada data test digunakan untuk mencocokkan apakah hasil prediksi dari HMM dengan model yang diberikan sudah sama dengan tag NE sebenarnya. Misal, ketika sebuah kata berlabel entitas sebenarnya **PERSON** namun dideteksi sistem sebagai **LOCATION**, maka entitas tersebut dihitung sebagai _false negative_. Contoh lain jika kata tersebut merupakan **LOCATION** dan diprediksi sebagai **LOCATION** maka dihitung _true positive_. Namun, jika kata tersebut merupakan **OTHER** tapi dideteksi sebagai **LOCATION** (atau tag NE yang lain) maka disebut sebagain _false positive_, sedangkan jika **OTHER** dideteksi sebagai **OTHER** berarti termasuk _true negative_.

Jika dalam teks data tes tidak ditemukan tag NE, tentu saja semuanya dianggap sebagai tag **OTHER**  yang kemudian hanya menghitung _true negative_ dan _false positive_ saja.

### Bonus
Penjelasan lebih lanjut mengenai precision, recall dan akurasi -> [Perbedaan: precision, recall & accuracy](https://dataq.wordpress.com/2013/06/16/perbedaan-precision-recall-accuracy/)
