### ISSUE TITLE
Hasil tag di prediction tidak bisa tampil

### ISSUE THREAD

**Issue by onynaraulita** [yusufsyaifudin/indonesia-ner#3]
Saya coba jalankan testprediction(), tapi tag ner nya tidak muncul. Ini output yg saya dapatkan:

74 [AWT-EventQueue-0] INFO yusufs.nlp.nerid.utils.POSTagger  - Jokowi pergi ke Singapura . 
74 [AWT-EventQueue-0] INFO yusufs.nlp.nerid.utils.POSTagger  - [{token=Jokowi, postag=NNPFC}, {token=pergi, postag=VBI}, {token=ke, postag=IN}, {token=Singapura, postag=NNFC}, {token=., postag=.}]

Mohon bantuannya..

**Comment by yusufsyaifudin** [comment]
sudah coba pakai embedded model?

```
IndonesiaNER iner = new IndonesiaNER(IndonesiaNER.MODEL.YUSUFS);
ArrayList<Sentence> predicted = iner.predictWithEmbeddedModel("Jokowi pergi ke Singapura.", true);
System.out.println(predicted);
```

**Comment by onynaraulita** [comment]
Wah, sudah bisa mas. Terima kasih mas..
