### ISSUE TITLE
Skripsi Muhammad Fachri - Pengenalan Entitas Bernama Pada Teks Bahasa Indonesia Menggunakan Hidden Markov Model 

### ISSUE THREAD

**Issue by onynaraulita** [yusufsyaifudin/indonesia-ner#4]
Halo mas, kebetulan saya sedang mengerjakan tugas akhir yang menggunakan NER HMM ini, dan saya ingin sekali untuk bisa mendapatkan softfcopy TA dari temen mas, yg bernama Muhammad Fachri dengan judul Pengenalan Entitas Bernama Pada Teks Bahasa Indonesia Menggunakan Hidden Markov Model . 

Saya sudah coba cari di internet, tapi belum dapat soft copy yg full. Jika berkenan, mohon bantuannya atau jika boleh mas yusuf membagikan kontak social media atau apapun itu, agar saya bisa berkontak langsung dengan mas Muhammad Fachrinya.  Karna saya ingin mendalami lebih dalam bagaimana cara kerja dari NER dengan HMM ini mas.

Maaf mengganggu dan merepotkan mas. Terima kasih banyak mas.

**Comment by yusufsyaifudin** [comment]
@onynaraulita terakhir kali saya kontak beliau dua tahun lalu menggunakan email ini fachri.muh64@gmail.com semoga masih bisa dihubungi, terima kasih

**Comment by onynaraulita** [comment]
Oke mas, terima kasih banyak..
